# Generated by Django 2.0.9 on 2018-11-16 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='index',
            field=models.CharField(default='', max_length=2),
            preserve_default=False,
        ),
    ]
